spring.application.name=app

# String de conexão
# spring.datasource.url=jdbc:sqlserver://srvrhsoft2025.database.windows.net:1433;databaseName=dbRhSoft;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.url=jdbc:sqlserver://srvrhsoft2025.database.windows.net:1433;database=dbRhSoft;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;


# Credenciais
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Driver JDBC 
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
api.security.token.secret=${JWT_SECRET:my-secret-key}
